["LADM_COL_V3_0.LADM_Nucleo.col_puntoReferencia.ue"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.COL_UnidadEspacial.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.ExtUnidadEdificacionFisica.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.ExtInteresado.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Clase_Via_Principal"]
form_order=4

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Codigo_Postal"]
form_order=3

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Complemento"]
form_order=12

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Es_Direccion_Principal"]
form_order=2

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Letra_Via_Generadora"]
form_order=9

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Letra_Via_Principal"]
form_order=6

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Localizacion"]
form_order=14

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Nombre_Predio"]
form_order=13

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Numero_Predio"]
form_order=10

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Sector_Ciudad"]
form_order=7

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Sector_Predio"]
form_order=11

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Tipo_Direccion"]
form_order=1

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Valor_Via_Generadora"]
form_order=8

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Valor_Via_Principal"]
form_order=5
